### ISSUE TITLE
Release a static tag

### ISSUE THREAD

**Issue by mmwtsn** [whilp/ssh-agent#16]
It would be great if there was a [tag on Docker Hub](https://hub.docker.com/r/whilp/ssh-agent/tags/) other than latest.

We've encountered a few broken builds in the past when relying on `latest` from other images and would love to be able to pin our version here as well.

**Comment by whilp** [comment]
Pushed tag v0.1; thank you!

**Comment by mmwtsn** [comment]
Awesome! Thanks for the quick response (and this project 👍).

**Comment by mmwtsn** [comment]
Is the new tag available on Docker Hub?

I'm not seeing it here: https://hub.docker.com/r/whilp/ssh-agent/tags/
