### ISSUE TITLE
ssh/config or known_hosts sharing?

### ISSUE THREAD

**Issue by rosskevin** [whilp/ssh-agent#2]
Unknown hosts are still a problem (anything from bitbucket or github).  Inside a container, both of these fail with `Host key verification failed`.  The main problem being that [docker-rails is creating/running non-interactive containers](https://github.com/alienfast/docker-rails/issues/19#issuecomment-145168248).  

For example, in container, these fail:

```
ssh -o 'StrictHostKeyChecking no' -T git@github.com
ssh -o 'StrictHostKeyChecking no' -T git@bitbucket.org
```

But these succeed

```
ssh -o 'StrictHostKeyChecking no' -T git@github.com
ssh -o 'StrictHostKeyChecking no' -T git@bitbucket.org
```

Is there a way to either share `ssh/config` with an exclusion or (perhaps better yet) `known_hosts`?

**Comment by whilp** [comment]
Yep; this should be doable by:
- renaming the exported volume in `Dockerfile` to `/root/.ssh`
- updating `SSH_AUTH_SOCK` to `/root/.ssh/agent`
- adding an instruction to optionally `docker run ... --volumes-from=ssh-agent -v ~/.ssh:/ssh whilp/ssh-agent cp /ssh/known_hosts /root/.ssh/known_hosts`

Wanna give it a try and PR?

**Comment by rosskevin** [comment]
EDIT: I see what you did (couldn't see before on my mobile).  I'm trying this now.

**Comment by rosskevin** [comment]
Everything works, pull request #3 takes care of it.  Thanks for the pointers.

**Comment by rosskevin** [comment]
Confirmed in my docker-compose environment as well.

**Comment by emilv** [comment]
Why is this closed when the PR is not merged yet?

**Comment by rosskevin** [comment]
I closed because I submitted a pull, perhaps that's no good?

**Comment by emilv** [comment]
You do not know yet if your PR will be merged :-) It's usually up to the maintainer to close issues when/if they merge a pull request.

**Comment by rosskevin** [comment]
@whilp PR #3 is ready to go, no conflicts, works great.

**Comment by whilp** [comment]
Thanks @rosskevin!

**Comment by whilp** [comment]
Hey @rosskevin, just a quick note that I've removed specific support for `known_hosts` in this image in 808a6bb. It prevented non-root agents (see #6) and is a bit orthogonal to the purpose of the image (which is to support ssh agents). That said, you should be able to achieve the same effect by creating a separate data volume and mounting that at `~/.ssh` (for root and non-root UIDs) just fine.

Thanks again for this contribution!

**Comment by rosskevin** [comment]
@whilp perhaps I'm particularly dense today, or that I've forgotten everything I wrote for this to work (I work on everything in our stack)...but I'm revisiting now and if you would be able to spell it out for me with some sample commands, I would appreciate it very much!  Making known_hosts available might make a nice update to your readme.  [This question has been viewed a lot on SO](http://stackoverflow.com/a/32911979/2363935) so I think it could be worthwhile

**Comment by rosskevin** [comment]
I spoke too soon and noticed my error, so this comment is a a work in progress (got to run for now):

This works, but makes host `.ssh` available fully inside the container (we don't want that):

```
# startup a container
docker run --rm -v ~/.ssh:/root/.ssh -it ubuntu bash
# make sure it has ssh [in container command]
apt-get update -qq && apt-get install -qy openssh-client
# check github access  [in container command]
ssh -o 'StrictHostKeyChecking no' -T git@github.com
```

I think what we want is to do something like this:

``` bash
# start the agent and add the key
docker run -d -v ssh:/ssh --name=ssh-agent whilp/ssh-agent:latest
docker run --rm -v ssh:/ssh -v $HOME:$HOME -it whilp/ssh-agent:latest ssh-add $HOME/.ssh/id_rsa

# create a 'kh' data container for container /root/.ssh 
xxx
# copy host known_hosts into 'kh' container 
xxx

# startup a demo container and mount the data container
docker run --rm -it -v ssh:/ssh -v [VOLUMES from 'kh' mounted at /root/.ssh] -e SSH_AUTH_SOCK=/ssh/auth/sock ubuntu /bin/bash -c "apt-get install -y openssh-client && ssh-add -l && ssh -o 'StrictHostKeyChecking no' -T git@github.com"
```

**Comment by whilp** [comment]
@rosskevin yeah, your approach seems fine. Roughly, you want to mount the `ssh` named volume on `/ssh` and set `SSH_AUTH_SOCK` accordingly. You can also mount another volume (perhaps called `known_hosts` over your user's `~/.ssh` and store a `known_hosts` file there. Alternatively, you can invoke `ssh` with `-o UserKnownHostsFile=/path/to/file` and stash the file wherever you'd like.

All of those approaches should work independently of `ssh-agent`, which is why I don't think we should solve for `known_hosts` in this container. Thanks again!
