### ISSUE TITLE
Sharing socket between non-root users

### ISSUE THREAD

**Issue by andrew-kurin** [whilp/ssh-agent#6]
Hi, first of all I want to thank you for the great solution, it works great for me if you run Docker container as root. The only issue I have at this moment is, when I'm trying to use ssh-agent for any non-root user, I'm not able to do that.
I've tried to set the same user_id/group in ssh-agent container, and then I mount the socket in /home/user/.ssh/socket

```
user@309fed97ea3b:/srv$ echo $SSH_AUTH_SOCK
/home/user/.ssh/socket
```

I've set 777 permissions on the socket itself

```
user@309fed97ea3b:/srv$ ls -la /home/user/.ssh/socket
srwxrwxrwx 1 user user 0 Apr 13 19:49 /home/user/.ssh/socket
```

But when I'm trying to do anything it gives me

```
user@309fed97ea3b:/srv$ ssh git@github.com
Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
Error writing to authentication socket.
Permission denied (publickey).
```

Is it possible to make socket sharing work with non-root user?

**Comment by whilp** [comment]
Hello! Thank you for filing this issue. This should be possible as of 189d072! The docs are updated as well, but:

``` console
docker run -d --name ssh-agent -u 1001 whilp/ssh-agent
docker run --volumes-from ssh-agent -u 1001 whilp/ssh-agent ssh-add -l
```

Any other containers you create with `-u 1001` and `--volumes-from ssh-agent` should be able to interact with the agent. Closing, but please reopen if you run into trouble!
