### ISSUE TITLE
Invalid volume destination path: '~/.ssh' mount path must be absolute..

### ISSUE THREAD

**Issue by jpswade** [whilp/ssh-agent#7]
`
$ docker run -u 1001 --rm --volumes-from=ssh-agent -v ~/.ssh:~/.ssh -it whilp/ssh-agent:latest ssh-add ~/.ssh/id_rsa
docker: Error response from daemon: Invalid bind mount spec "/Users/user/.ssh:~/.ssh": Invalid volume destination path: '~/.ssh' mount path must be absolute..
See 'docker run --help'.
`

Workaround:

`docker run --rm --volumes-from=ssh-agent -v ~/.ssh/:/.ssh/ -it whilp/ssh-agent:latest ssh-add /.ssh/id_rsa`

**Comment by whilp** [comment]
Thank you -- should be fixed in 4b59b0b!
