### ISSUE TITLE
What is the purpose of the -v ssh:/ssh item in the examples?

### ISSUE THREAD

**Issue by opichon** [whilp/ssh-agent#8]
Hi, in all your example commands you include `-v ssh:/ssh`. What is the purpose of this? As I understand, this mounts a local `ssh` directory as `/ssh/` on the long-running agent container.

Previous documentation (and some examples in the issues) would use instead `--volumes-from ssh-agent`.

**Comment by mickaelperrin** [comment]
This is a named volume, have a look at #7

**Comment by opichon** [comment]
Sorry to belabour the point: In short, this represents the mapping of the ssh directory on the host to the ssh directory of the user in the container. Since root is the default user in the container, and since `.ssh` is the usual ssh directory, wouldn't `~/.ssh:/root/.ssh` be less confusing?

**Comment by mickaelperrin** [comment]
No, the named volume mounts nothing from the host. it creates a volume in the "main" docker container that will be shared with the other containers that need to access the agent.

The mount of the ssh host folder is done through the `-v $HOME:$HOME` in the command

```
docker run -u 1001 --rm -v ssh:/ssh -v $HOME:$HOME -it whilp/ssh-agent:latest ssh-add $HOME/.ssh/id_rsa
```

**Comment by opichon** [comment]
Could you expand on this a little? is this required or optional?

**Comment by mickaelperrin** [comment]
```
docker run -u 1001 -d -v ssh:/ssh --name=ssh-agent whilp/ssh-agent:latest
```

creates the container that will hold all imported keys. There is no mount between the host and the container.

```
docker run -u 1001 --rm -v ssh:/ssh -v $HOME:$HOME -it whilp/ssh-agent:latest ssh-add $HOME/.ssh/id_rsa
```

or if you prefer

```
docker run -u 1001 --rm -v ssh:/ssh -v ~/.ssh:/tmp/ssh -it whilp/ssh-agent:latest ssh-add /tmp/ssh/id_rsa
```

1/ creates a _temporary_ container that mounts:
- the /ssh folder from the main container
- the $HOME directory of the user running the docjer command in the $HOME directory of the user in the docker container (id 1001)

2/ launch the command ssh-add. It "copies" the key `id_rsa` from the host to the container

3/ destroy the temporary container

Your key is now in the main container.

To use it in new containers, you have to mount the ssh folder of the first container with the option `-v ssh:/ssh` and pass an environment variable that tells your new container where to find your keys `-e SSH_AUTH_SOCK=/ssh/auth/sock`.

**Comment by whilp** [comment]
Thanks, @mickaelperrin -- quite right!

**Comment by opichon** [comment]
Thanks for this. I can now make it work as per above by running docker commands.

**Comment by mickaelperrin** [comment]
@whilp You're welcome, thanks for your project, really useful !
