### ISSUE TITLE
Could not open a connection to your authentication agent

### ISSUE THREAD

**Issue by opichon** [whilp/ssh-agent#9]
I am afraid that I cannot make the latest version to work 

I can add a key, read it using a transient whilp/ssh-agent container, but I cannot read it from another container.

```
docker run -u 1001 -d  --name=ssh-agent whilp/ssh-agent:latest
docker run -u 1001 --rm --volumes-from ssh-agent -v $HOME:$HOME -it whilp/ssh-agent:latest ssh-add $HOME/.ssh/id_rsa 
docker run -u 1001 --rm --volumes-from ssh-agent -it whilp/ssh-agent:latest ssh-add -l
```

so far so good. However this fails with the error "Could not connect to your authentication agent".

```
docker run -u 1001 --rm --volumes-from ssh-agent -e SSH_AUTH_SOCK=/ssh/auth/sock -it polifonic/php56:latest ssh-add -l
```

**Comment by opichon** [comment]
Somehow it now works. Not sure why, but I'm closing this ticket.

**Comment by whilp** [comment]
Hm -- thanks for reporting (and closing); please re-open if you observe this again!
